### ISSUE TITLE
Example of linking publications and data from Data Conservancy

### ISSUE THREAD

**Issue by MonicaDuke** [alex-ball/HowTo-CiteDatasets#18]
A pilot carried out with arXiv.org.  The pilot ended in 2013 and in 2015 the data from the pilot was merged into
See  arXiv http://arxiv.org/help/data_conservancy
and from http://dataconservancy.org/software/ (Integrations with software, bottom of page):
"Authors submit a paper for publication, along with their data, to arXiv.org.  Upon receipt, the article remains with the arXiv system, while the data are deposited to the JHU Data Conservancy Instance.  A bi-directional link is established between the paper in arXiv and the data in Data Conservancy.  The arXiv pilot uses the search, access, and ingest APIs."

**Comment by alex-ball** [comment]
This is not an ideal example, due to the fact that the data has indeed been merged back into arXiv as supplementary information, eliminating the (need for) linkage with the JHU Data Conservancy.

Had the guide been revised a year or two ago, this example would have been included but I think the time for it has passed.
